// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYgta_ORsY6GXUgNSiKdMwaKoeICjtTgY',
    appId: '1:619436709613:web:be9e60687f5b68a5005ee4',
    messagingSenderId: '619436709613',
    projectId: 'kamaapp-f8b86',
    authDomain: 'kamaapp-f8b86.firebaseapp.com',
    storageBucket: 'kamaapp-f8b86.appspot.com',
    measurementId: 'G-4NEH46WY9B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkVxWO4p26uz4p_yfn39btDj6sbQZ0xCE',
    appId: '1:619436709613:android:af07c1359eab7155005ee4',
    messagingSenderId: '619436709613',
    projectId: 'kamaapp-f8b86',
    storageBucket: 'kamaapp-f8b86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4w77MOja4_K1IVNGoiBYtIORulA9Jozw',
    appId: '1:619436709613:ios:5b25201a745c5298005ee4',
    messagingSenderId: '619436709613',
    projectId: 'kamaapp-f8b86',
    storageBucket: 'kamaapp-f8b86.appspot.com',
    iosBundleId: 'com.example.kamaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4w77MOja4_K1IVNGoiBYtIORulA9Jozw',
    appId: '1:619436709613:ios:2afbed0aa526e70e005ee4',
    messagingSenderId: '619436709613',
    projectId: 'kamaapp-f8b86',
    storageBucket: 'kamaapp-f8b86.appspot.com',
    iosBundleId: 'com.example.kamaApp.RunnerTests',
  );
}
